version: '3.1'

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGODB_DATABASE: api_indelpro
    volumes: 
      - ./mongo:/data/db